server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/game_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update